### ISSUE TITLE
Run update on extention pack

### ISSUE THREAD

**Issue by SSmale** [microsoft/vscode-generator-code#118]
I created an extention pack the other day and have now installed some more extentions to my system that I would like to add to the pack. I don't see a clean way to do this, other than create a new pack, copy over the code and then delete the project.

Any insight into the best way of doing this?

**Comment by aeschli** [comment]
@sandy081 Can you help?

**Comment by sandy081** [comment]
@SSmale Why not updating the pack with new extensions and publish it?

**Comment by SSmale** [comment]
@sandy081 How do I update the pack? 

When I use `yo code` I only get the option to create a new extension pack not to update a current one, when I have that project open.

**Comment by sandy081** [comment]
You cannot update an extension using Yo code I suppose. You have to open the existing pack project and update `extensionDependencies` in `package.json`. Increase the version and push to market place

**Comment by SSmale** [comment]
how would I get the list of the current extensions to be able to update `extensionDependencies`?

**Comment by sandy081** [comment]
You can get the id of the extension when you open it.. Eg: `ms-python.python` below

![image](https://user-images.githubusercontent.com/10746682/42087953-173b0f82-7b98-11e8-8847-7689ee1a311c.png)

**Comment by SSmale** [comment]
Thank you for the assist. 

`code --list-extensions` is a good way to see your current things to update the pack
