### ISSUE TITLE
We found a potential security vulnerability in one of your dependencies

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-generator-code#119]
![image](https://user-images.githubusercontent.com/900690/42074300-ba6cdb0e-7b6b-11e8-9140-89d6e5d32994.png)

Looks like this originates from node-growl.

![image](https://user-images.githubusercontent.com/900690/42074315-e13dafa6-7b6b-11e8-96d4-bfe38059e5ab.png)

**Comment by aeschli** [comment]
fixed by https://github.com/Microsoft/vscode-generator-code/commit/62090f1df9acba45561716050044f7f2fa9cd5ee
