### ISSUE TITLE
Add "while" key to patterns in tmLanguage JSON schema

### ISSUE THREAD

**Issue by silvenon** [Microsoft/vscode-generator-code#122]
`*.tmLanguage.json` files also support the `while` pattern key, but the [attached JSON schema](https://github.com/martinring/tmlanguage/blob/master/tmlanguage.json) doesn't allow it.

```json
{
  "begin": "^foo",
  "while": "^(?!\\s*$)",
  "patterns": []
}
```

I'm not sure what the best thing to do here is. Maybe create a new repo with an updated schema?

**Comment by aeschli** [comment]
@silvenon Can you make a PR directly against https://github.com/martinring/tmlanguage/blob/master/tmlanguage.json ?

Thanks a lot!
