### ISSUE TITLE
Publish experience for new contributers

### ISSUE THREAD

**Issue by sana-ajani** [Microsoft/vscode-generator-code#129]
I created my first extension recently, and the publish experience was slightly confusing. 

- Yeoman generator doesn't indicate if you've entered a unique publisher or existing publisher for "publisher-name". If you actually use a unique publisher and try logging in with vsce to that publisher, it's not actually been created:

![publish name](https://user-images.githubusercontent.com/9721254/45850307-6d7bd000-bcea-11e8-84cc-79118a006a17.PNG)

![publish name error](https://user-images.githubusercontent.com/9721254/45850316-753b7480-bcea-11e8-9ba5-5cd747b8d334.PNG)

- If you end up using an existing publisher name during the prompt, you do not realize it until you try to vsce publish, and then have to go through the following steps to create a new unique one and change package.json (which isn't included in the docs):

1. Create extension from Yeoman generator with publisher name "test123"
2. Create PAT 
3. Login to publisher -> option to overwrite PAT -> y -> Authentication successful, found publisher test12 (this is another existing one, but obviously also not mine)
4. Try to publish -> Access denied
5. Create new unique publisher
6. Try to publish -> Access denied
7. Have to change publisher name in package.json and then republish

If there's a way for first time users who don't have a publisher name when going though the "yo-code" set up to actually create one then, it would reduce a lot of the above confusion.

**Comment by aeschli** [comment]
I agree that it would be better if the user doesn't need to bother about the publisher until actually publishing.

I created https://github.com/Microsoft/vscode/issues/59730 and https://github.com/Microsoft/vscode-vsce/issues/293.

We can update the generator after the october release
