### ISSUE TITLE
Consider updating MIT license text with year

### ISSUE THREAD

**Issue by peterblazejewicz** [Microsoft/vscode-generator-code#13]
The MIT templates use year:
https://tldrlegal.com/license/mit-license#fulltext
The template generated via GitHub has that information, the same with other MS project hosted here, e.g.:
https://github.com/Microsoft/Virtualization-Documentation/blob/master/LICENSE.md
https://github.com/Microsoft/vscode-mock-debug/blob/master/LICENSE.txt
The project license is missing it:
https://github.com/Microsoft/vscode-generator-code/blob/master/LICENSE
Thanks!

**Comment by chrisdias** [comment]
Actually, we (Microsoft) have chosen to NOT put dates in the license, otherwise we end up changing these things every year.  We should revert this change.
