### ISSUE TITLE
Publish an offline .vsix realease 

### ISSUE THREAD

**Issue by Gedd18** [Microsoft/vscode-generator-code#130]
Like C++ Extension, vscode-generator-code needs to download some packages. In an offline environment or a proxy behind locked environment, it is not possible. 

The solution brings by C++ Extension is to produce specific release with already downloaded requisites and dependencies. These releases are only available on github repository but they are mentionned in documentation.

An offline release is surely more heavy but the need for developping extension in offline environment is real.

**Comment by aeschli** [comment]
vscode-generator-code doesn't need to download additional packages to run. It triggers 'npm install' at dokr point. It that what you mean?
Also what it does is checking the VSCode repo for what the latest version is. But If that request can not be made, we fall back to know version.

**Comment by Gedd18** [comment]
In fact it cannot be installed in an offline environmentwith "npm instal" or "npm install --production.
Here the log :

npm ERR! network getaddrinfo ENOTFOUND
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "--production"
npm ERR! cwd /home/xxxxx/xxx/xxxxx/xxxx/vscode-generator-code-1.1.38
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! syscall getaddrinfo
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/xxxx/xxx/xxx/xxxxxxx/vscode-generator-code-1.1.38/npm-debug.log
npm ERR! not ok code 0

**Comment by aeschli** [comment]
When running `npm install', the generator will issue an error.

We currently have no plans on bundling the dependencies
