### ISSUE TITLE
Fails at the installation

### ISSUE THREAD

**Issue by xAndreMCx** [Microsoft/vscode-generator-code#135]
When I ran `npm install -g generator-code`  it failed.

yo@2.0.5 postinstall C:\Users\Andre\AppData\Roaming\npm\node_modules\yo
yodoctor

yodoctor is not recognized as an internal or external command,
operable program or batch file.
npm WARN rollback Rolling back kind-of@3.2.2 failed (this is probably harmless): EPERM: operation not permitted, lstat 'C:\Users\Andre\AppData\Roaming\npm\node_modules\yo\node_modules\object-copy\node_modules'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! yo@2.0.5 postinstall: yodoctor
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the yo@2.0.5 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Andre\AppData\Roaming\npm-cache\_logs\2018-10-12T13_11_16_856Z-debug.log

Can someone help me, please.

**Comment by aeschli** [comment]
You have to file this against yeoman
