### ISSUE TITLE
Git related files are still created even when not creating a git repo

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode-generator-code#137]
During JavaScript extension generation, `.gitattributes` and `.gitignore` are still created, even though I specified I didn't want a git repo.

**Comment by grabartley** [comment]
I would like to contribute, could I possibly work on this?

**Comment by aeschli** [comment]
@grabartley Yes of course, 3 days remaining!  :-)

**Comment by grabartley** [comment]
[PR#141](https://github.com/Microsoft/vscode-generator-code/pull/141)
