### ISSUE TITLE
Consider adopting .editorconfig for the project

### ISSUE THREAD

**Issue by peterblazejewicz** [Microsoft/vscode-generator-code#14]
Now VSCode supports EditorConfig file via extension:
https://marketplace.visualstudio.com/items/chrisdias.vscodeEditorConfig
it could be useful for the project to add `.editorconfig` file to avoid huge differences between source formatting (and between commits), e.g.:
https://github.com/Microsoft/vscode-generator-code/blob/master/package.json
https://github.com/Microsoft/vscode-generator-code/blob/master/jsconfig.json
Thanks!

**Comment by bpasero** [comment]
No plans atm.
