### ISSUE TITLE
'publisher' is a mandatory property in package.json

### ISSUE THREAD

**Issue by krist00fer** [Microsoft/vscode-generator-code#143]
PR #139 removed the ask for publisher but also removed the output of any kind of publisher to the package.json file. This causes new extensions to fail to load with error message:

> [C:\src\ext001]: property `publisher` is mandatory and must be of type `string`

Either revert and ask for publisher again or add a static publisher name in package.json to comply with required scheme of the file.

**Comment by egamma** [comment]
@krist00fer the change to the yo generator requires a change that will be in 1.29. There you will no longer get the runtime error and the user is warned when the extension is published.

So what happened is that the yo code module got published too soon. We will rollback the change and re-publish once 1.29 is out.

**Comment by krist00fer** [comment]
Thanks @egamma , I think I'm lost in the versions though :-) I thought I had version:

> +-- generator-code@1.1.39

1.29 seems to be something else. What did I miss? And do we have any timeline when 1.29 is going to be out?

**Comment by egamma** [comment]
@krist00fer 

>1.29 seems to be something else. 

Sorry, this referred to the version of VS Code. The current stable version is 1.28 and 1.29 will be shipped in the next couple of days.

**Comment by egamma** [comment]
The change is rolled back, can you please confirm that it works again for you.

**Comment by krist00fer** [comment]
I ran

> npm install -g generator-code

... again and now I got the updated 1.1.40 and now I get the question of Publisher and the package.json file include the needed property. Thank you @egamma for your awesome support

**Comment by egamma** [comment]
Thanks for verifying! I'll close the issue.

**Comment by sw-yx** [comment]
i was on a 2 month old vscode version. updating to 1.29.1 fixed it

**Comment by aeschli** [comment]
@rahullli Where do you see this error?

**Comment by anoushk1234** [comment]
my code version is 1.57 and i update generator code too but it seems like the folder location is wrong for this error: property `engines` is mandatory and must be of type `object`,

**Comment by anoushk1234** [comment]
> 
> 
> my code version is 1.57 and i update generator code too but it seems like the folder location is wrong for this error: property `engines` is mandatory and must be of type `object`,

The issue was that i wasnt working in the root folder of my extension file
