### ISSUE TITLE
TS extension created can not launched correctly.

### ISSUE THREAD

**Issue by wraith13** [Microsoft/vscode-generator-code#145]
https://github.com/Microsoft/vscode-generator-code/blob/master/generators/app/templates/ext-command-ts/package.json#L15
```"main": "./out/extension",``` is wrong path.
Correctly it is ```"main": "./out/src/extension",``` .

**Comment by gregvanl** [comment]
I think the current package.json value is correct. I just created a new TypeScript extension and the Hello World extension launched correctly for me.

Here is what I see in the projects `out` directory:

![image](https://user-images.githubusercontent.com/12818376/49036237-0ce69480-f16c-11e8-9ccf-1cb77b022267.png)

Closing the corresponding PR until we understand your issue.

**Comment by wraith13** [comment]
Sorry, You are right! It's my fault!
I understood this problem. In order to apply my favorite TypeScript settings, I copied `tsconfig.json` from other extension created by old generators.
Old `rootDir` is ".", and new one is "src".
