### ISSUE TITLE
Simplify the getting starting experience

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode-generator-code#148]
Currently, if you run `yo code` and select `TS`, there are 7 additional questions you need to answer. Most of these are irrelevant to beginners.

```
? What type of extension do you want to create? New Extension (TypeScript)
? What's the name of your extension? testts
? What's the identifier of your extension? testts
? What's the description of your extension?
? Enable stricter TypeScript checking in 'tsconfig.json'? Yes
? Setup linting using 'tslint'? Yes
? Initialize a git repository? Yes
? Which package manager to use? npm
```

I suggest introducing another option that happens right after choosing `TS` type of extension

```
? What type of extension do you want to create? New Extension (TypeScript)
? Use default config or manually set config? (`default` and `manual` are two options. `default` is default.)
? What's the name of your extension? test
```

That's it for beginners. All fields are set:

- identifier: same as `name`
- description `${name} extension`
- stricter: yes, same as default
- setup linting: yes, same as default
- init git: yes, same as default
- which pkg manager: `npm`, same as default

If someone choose manual config, let him config everything as he had done before.

What do you think, @bpasero?

**Comment by usernamehw** [comment]
Is it possible to save the above options just like `git` global config?

**Comment by aeschli** [comment]
Discussed with @egamma and we decided to remove the tsint and strict prompts to simplify the `yo code` experence. Both are now on by default. 293c5c6781b485928daacb95b71cc21278e27f46
