### ISSUE TITLE
Debugging extensions based on the Javascript generator works, those on Typescript timeout

### ISSUE THREAD

**Issue by jimthedev** [Microsoft/vscode-generator-code#15]
I think I've outlined this pretty well here:

http://stackoverflow.com/questions/33811221/visual-studio-code-extension-host-timeout-during-debugging

Basically the problem is that when I actually try to debug the extension, those based on Typescript just result in timeouts of both sides of the debugging workflow.

In Javascript everything seems to work properly. I'm not sure if this is just a race condition based on the fact that the typescript must be compiled and thus pushes it outside the 3000ms timeout that Code seems to be willing to wait.

**Comment by bpasero** [comment]
@isidorn please chime in

**Comment by isidorn** [comment]
In 0.10.1 we actually do not wait for the gulp task to [finish](https://github.com/Microsoft/vscode/issues/170) before starting debug, so that should not be the cause fo the timeout.
I tried your scenario and it works for me.

Forwarding to @weinand

**Comment by bpasero** [comment]
Please move this over to https://github.com/Microsoft/vscode/

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-node-debug#9
