### ISSUE TITLE
vsce package fails with `Error: Missing publisher name`

### ISSUE THREAD

**Issue by bingoabs** [Microsoft/vscode-generator-code#150]
I follow the [Hello World ](https://code.visualstudio.com/api/get-started/your-first-extension) extension and finish a project for my desire.

But after I run the debug mode normally, I can not `vsce package`。And then I follow the [Publish Extension](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#publishing-extensions) to get a `Personal Access Token` and `login` successfully, the `vsce package` still raise the same error.

Someone can help me? I am confused, because no words say what I had to do before `vsce package`.

Thanks a lot

**Comment by usernamehw** [comment]
Do you have `"publisher"` in your `package.json`?

Like that:

https://github.com/kisstkondoros/gutter-preview/blob/5f442ae15c5a4d94c532d552fe3cbbe81d3b5964/package.json#L6

**Comment by bingoabs** [comment]
> Do you have `"publisher"` in your `package.json`?
> 
> Like that:
> 
> https://github.com/kisstkondoros/gutter-preview/blob/5f442ae15c5a4d94c532d552fe3cbbe81d3b5964/package.json#L6

@usernamehw  Thanks a lot. Follow your tips, I already finish the extension.
