### ISSUE TITLE
[feature request] add webpack bundled extension templates.

### ISSUE THREAD

**Issue by LeuisKen** [microsoft/vscode-generator-code#163]
When I start an extension project, I use `yo code` typescript template, but when I using `vsce package` to build `.vsix`, the following notice:

![image](https://user-images.githubusercontent.com/7701575/54992295-e6d9df80-4ff9-11e9-839b-dc14b10395e2.png)

So I have to migrate my existing extension since there is no webpack bundled extension templates I can use.

Would your like to add this template ? I think it could help the extension developers a lot.

Thanks a lot.    : )

**Comment by aeschli** [comment]
We're not sure if this isn't adding too much complexity for a starter extension. Typically you add bundling at a later stage and the steps in https://code.visualstudio.com/api/working-with-extensions/bundling-extension explain what you have to do to add packing to an existing extension.

**Comment by LeuisKen** [comment]
I understand what you're worrying about, but since there is no bundled template, I have to repeat this work whenever start a new extension project. Is there any way to avoid this problem?

**Comment by tjx666** [comment]
@LeuisKen  Maybey you need [vscode-extension-boilerplate](https://github.com/tjx666/vscode-extension-boilerplate)

**Comment by LeuisKen** [comment]
thx
