### ISSUE TITLE
Bug: Generator Fails To Create 'Compile' Script

### ISSUE THREAD

**Issue by Tbhesswebber** [microsoft/vscode-generator-code#169]
According to everything that I can find, but primarily the [VSCode documentation on CI](https://code.visualstudio.com/api/working-with-extensions/continuous-integration) and their example `build.yml`, there should be a `compile` script provided by this generator. 

Wait... Does this only exist for TypeScript extensions?  If so, that should be mentioned in the VSCode CI docs because they just tell you to copy-pasta a the yaml file, but that means this issue should go get lost in the 5000 open issues they have.

```json
// package.json (unchanged)
{
	"name": "delete-me",
	"displayName": "delete me",
	"description": "delete me",
	"version": "0.0.1",
	"engines": {
		"vscode": "^1.33.0"
	},
	"categories": [
		"Other"
	],
	"activationEvents": [
		"onCommand:extension.helloWorld"
	],
	"main": "./extension.js",
	"contributes": {
		"commands": [
			{
				"command": "extension.helloWorld",
				"title": "Hello World"
			}
		]
	},
	"scripts": {
		"postinstall": "node ./node_modules/vscode/bin/install",
		"test": "node ./node_modules/vscode/bin/test"
	},
	"devDependencies": {
		"typescript": "^3.3.1",
		"vscode": "^1.1.28",
		"eslint": "^5.13.0",
		"@types/node": "^10.12.21",
		"@types/mocha": "^2.2.42"
	}
}```

**Comment by aeschli** [comment]
Yes, compile is only needed for TypeScript.

I created https://github.com/microsoft/vscode-docs/issues/2673 to improve the CI docs.
