### ISSUE TITLE
.tmLanguage.json import doesn't work, expects plist-XML

### ISSUE THREAD

**Issue by synchronos-t** [microsoft/vscode-generator-code#172]
I tried to use Yeoman to extend CSS highlighting support (to make it handle CSS files with HubL markup). So, I tried to import the [built-in syntax files](https://github.com/microsoft/vscode/blob/master/extensions/css/syntaxes/css.tmLanguage.json) from VSCode repository, according to [these instructions](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#developing-a-new-grammar-extension), which say the `yo code` should support `.tmLanguage.json` files.

However, if I try to do that, I get an error `Unhandled error. (Language definition file does not contain 'DOCTYPE plist'. Make sure the file content is really plist-XML.)` (I also get the same error if I try to import the exact URL that is in the example picture.) It also doesn't matter if I use the GitHub page URL, the raw URL, or a local file.

Just installed these, so they ought to be the newest ones:
yo@2.0.6
generator-code@1.1.50

**Comment by t-dimaras** [comment]
Same

> events.js:189
    throw err; // Unhandled 'error' event
    ^
>
>Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Language definition file does not contain \'DOCTYPE plist\'. Make sure the file content is really plist-XML.')
    at module.exports.emit (events.js:187:17)
    at Immediate.setImmediate (D:\Users\thodoris\AppData\Roaming\npm\node_modules\generator-code\node_modules\yeoman-generator\lib\index.js:433:22)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

yo@3.1.0
generator-code@1.2.1

**Comment by npulidomateo** [comment]
I have this issue too.  [`2c08bc8`](https://github.com/microsoft/vscode-generator-code/commit/2c08bc86a8c81b68bcf0966a2f40b27c0e18b1f1) seems not to have resolved it?

```
? What type of extension do you want to create? New Language Support
Enter the URL (http, https) or the file path of the tmLanguage grammar or press ENTER to start with a new grammar.
? URL or file to import, or none for new: https://github.com/davidrios/pug-tmbun
dle/blob/master/Syntaxes/Pug.JSON-tmLanguage
events.js:307
    throw err; // Unhandled 'error' event
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ("Language definition file does not contain 'DOCTYPE plist'. Make sure the file content is really plist-XML.")
    at module.exports.emit (events.js:305:17)
    at module.exports.EventEmitter.emit (domain.js:485:12)
    at Immediate._onImmediate (/usr/lib/node_modules/generator-code/node_modules/yeoman-generator/lib/index.js:668:20)
    at processImmediate (internal/timers.js:456:21)
    at process.topLevelDomainCallback (domain.js:137:15) {
  code: 'ERR_UNHANDLED_ERROR',
  context: "Language definition file does not contain 'DOCTYPE plist'. Make sure the file content is really plist-XML."
}
```

yo@3.1.1
generator-code@1.2.11
