### ISSUE TITLE
'yo code' freezes while trying to provide the name for the application

### ISSUE THREAD

**Issue by hemchander23** [microsoft/vscode-generator-code#173]
I've tried it from my Mac (node 8) as well as Windows machines (node 10):

The generator hangs exactly where I need to provide the name. Let me know if I am doing something wrong.

![image](https://user-images.githubusercontent.com/19341550/59867055-bf04d880-93aa-11e9-9b9e-dbf74cecdc32.png)

**Comment by HoLLy-HaCKeR** [comment]
Having the exact same issue. Won't even respond to CTRL+C. For some reason this always happens on the second input (when using `yo code`, on the name input, when using `yo` it will freeze on the extension type).

**Comment by HoLLy-HaCKeR** [comment]
yeoman/yeoman#1714 mentions that inquirer v6.4.0 introduced this issue, downgrading it should fix the issue.

**Comment by gtala** [comment]
i have the same problem in Windows 10

**Comment by dalenewman** [comment]
@HoLLy-HaCKeR 's suggestion worked for me.   I have Windows 10.
- Navigated to _%USERPROFILE%\AppData\Roaming\npm\node_modules\yo_
- `npm uninstall inquirer` 
- `npm install inquirer@6.3.1`

**Comment by HoLLy-HaCKeR** [comment]
Inquirer 6.4.1 has been published, which has a fix.

**Comment by aeschli** [comment]
A inquirer issue, fixed now
