### ISSUE TITLE
Generator for snippets is a converter and not a generator

### ISSUE THREAD

**Issue by Tanato** [Microsoft/vscode-generator-code#18]
Allow snippets generator to create a new structure for code snippets when it don't find a existent snippet to convert.

The documentation (and genetator name) is not clear about what it really do. 
"New Code Snippets" seems that it will create a new structure, not convert an existent snippet

**Comment by danielo515** [comment]
I have been trying to build a new snippets extension from scratch and I was unable to execute the full generator. What is the expected way to create a new extension snippet?

**Comment by aeschli** [comment]
All you actually need is a package.json with a `contributes` section pointing to your snippet file:
https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributessnippets

The snippet file follows the syntax as used for https://code.visualstudio.com/docs/customization/userdefinedsnippets

**Comment by danielo515** [comment]
Yeah, I came to that conclusion, but after spending some extra time. The point about a generator is to not waste any time.

**Comment by peterblazejewicz** [comment]
This is a bug in UX, not a feature request. I've also wasted a time, before realising my mistake (and later I've found this issue)

**Comment by prometheas** [comment]
Yea. The fact that this can't _generate_ a snippets extension (but can only _convert_ one) is just bizarre.

**Comment by prometheas** [comment]
@Tanato, @danielo515, and @peterblazejewicz - see my PR above… if you guys want to start using this sooner than later, feel free to `npm link` my branch.

**Comment by danielo515** [comment]
Dear @prometheas I will
Many thanks

**Comment by aeschli** [comment]
PR pushed. Thanks @prometheas!

**Comment by aeschli** [comment]
The new version of the generator will be pushed once the March release of VSCode is published (some time this week)
