### ISSUE TITLE
Selecting extension type skips two rows at a time

### ISSUE THREAD

**Issue by hackf5** [microsoft/vscode-generator-code#180]
After running `yo code` and being presented with the options, when using the up and down arrows the selection moves up or down by two items, i.e. it skips one. As there are an even number of entries it means half cannot be selected with the arrow keys.

This happens in powershell and cmd (Windows 10).

I've tried two keyboards and get the same result. I've never seen this behaviour anywhere else, so it doesn't look like a hardware issue.

I can see that there is a workaround by using the number keys to select the item, but I only worked this out by trying to use the number pad with numlock turned off.

**Comment by aeschli** [comment]
I'm not able to reproduce (Windows 10, 1903), but this is all controlled by the yo generator.
Can you file this against https://github.com/yeoman/generator/issues ?
