### ISSUE TITLE
TypeScript HelloWorld does not work

### ISSUE THREAD

**Issue by liweili50** [microsoft/vscode-generator-code#185]
hi, I use this cli created a helloworld demo,but it didn't open a new window only start debug when I runing extension.

MacOs 10.14.5
Node 12.9.0
VS Code 1.40.1

**Comment by aeschli** [comment]
Can you give more details?
You created the sample, opened vscode on the new folder and pressed `F5` ?

**Comment by aeschli** [comment]
Closing due to missing additional information.
