### ISSUE TITLE
Generator for Language Support should work even if no URL/File is informed

### ISSUE THREAD

**Issue by alefragnani** [Microsoft/vscode-generator-code#19]
Today, there is no way to start a _fresh_ language, without informing a URL of File to _convert_. You have to inform something.

The `yo code` generator should have a template inside itself _(maybe even the ant.tmLanguage)_, that could be used, instead of forcing a _conversion_ process. 

By the way, if you choose the `ant.tmLanguage` sample, but defines another name for your language (like **xisto**), it creates the package with your new name (**xisto**), but the `.tmLanguage` file is generated as **ant.tmLanguage**. The `package.json` file also refers the `path` to `ant.tmLanguage`.

Thanks

**Comment by wholroyd** [comment]
If you do provide an example file, would it be possible to use the JSON format, or include both and then put a blurb in the readme about the file differences (one is the original/throwback version while the other is provides the same features using json and is easier to read)?
