### ISSUE TITLE
Generator not working [node=v11.13.0/v10.15.1 npm=6.7.0]

### ISSUE THREAD

**Issue by nishants** [microsoft/vscode-generator-code#193]
**Steps to reproduce :** 
For npm version **6.7.0**.  and  node versions **v11.13.0** and **v10.15.1**

```bash
npm install -g yo generator-code
yo code
# Error code

# You don't seem to have a generator with the name code installed.
# You can see available generators with npm search yeoman-generator and then install them with npm install [name].
# To see the 2 registered generators run yo with the `--help` option.
```

Though when I run `npm search yeoman-generator`, I can see it installed : 
```
generator-code            | Yeoman generator…    | =aeschli…       | 2020-01-31 | 1.2.10   | yeoman-generator vscode visual studio visual st
```

**Comment by aeschli** [comment]
I believe `npm search yeoman-generator` just searches the npm registry, not what you have installed.

What does `yo --help` show?

Note that this is

**Comment by aeschli** [comment]
Closing due to lack of information

**Comment by phoenixeliot** [comment]
I also had this problem today and the workaround was to install `generator-code` locally (`npm install generator-code` with no `-g`). If I installed it globally, `yo --generators` would not list it. I'm not sure why.

I also had to uninstall and reinstall `yo` before this; my previous install was fairly old at this point.

**Comment by phoenixeliot** [comment]
Just an update on this, after running into it again. This seems to have been resolved by running `nvm use 12` (or 14, or probably any version) before `yo code`. I suspect this is failing due to my NVM setup being a little bit wonky.
