### ISSUE TITLE
Unable to find module 'grouped-queue/lib/subqueue'

### ISSUE THREAD

**Issue by jsumners** [microsoft/vscode-generator-code#194]
I did a fresh `npm install -g yo generator-code` (have not had any use for `yo` outside of this) and the subsequent `yo code` resulted in:

```
Error: Cannot find module 'grouped-queue/lib/subqueue'
```

The most recent version that works is `npm install -g generator-code@1.2.8`.

**Comment by aeschli** [comment]
I'm not able to reproduce. Can you try again with the latest version?

**Comment by jsumners** [comment]
![image](https://user-images.githubusercontent.com/321201/75608590-e5991880-5ace-11ea-897c-772f9427888c.png)

**Comment by aeschli** [comment]
Looks like a dup of https://github.com/yeoman/generator/issues/1189
Please update yo. 
I also updated our code to the latest.
