### ISSUE TITLE
need a gitignore file for vscode extension project skeleton

### ISSUE THREAD

**Issue by ORESoftware** [microsoft/vscode-generator-code#195]
https://code.visualstudio.com/api/get-started/your-first-extension

when this project is created with yoeman, there is no gitignore file. there should be a gitignore file which ignores node_modules at the very least.

i copied this ticket to: https://github.com/yeoman/generator/issues/1199

not sure where to file this ticket but please bear with me, thx

**Comment by aeschli** [comment]
That with `yo code` right?

There is a `.gitignore` file created, are you sure?
![image](https://user-images.githubusercontent.com/6461412/77165510-be70ae00-6ab2-11ea-8082-820788dbc431.png)
