### ISSUE TITLE
npm run test hangs indefinitely

### ISSUE THREAD

**Issue by emilykay2** [microsoft/vscode-generator-code#197]
I used the code generator and tried to run `npm run test` out of the box. It downloaded vscode, but then just hung for several minutes before I finally stopped the process.

**Comment by aeschli** [comment]
I'm not able to reproduce. Maybe a connection issue?

**Comment by emilykay2** [comment]
Probably connection related, so I just downloaded and unzipped vscode manually and put it in the .vscode-test folder and that worked
