### ISSUE TITLE
Generated tsconfig.json shows a warning

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-generator-code#20]
Generate an extension using yo code > typescript

The generated tsconfig.json shows up with a warning
![tsconfig](https://cloud.githubusercontent.com/assets/172399/11935852/811d6a62-a80a-11e5-9d46-10a35a8e6d07.png)

**Comment by aeschli** [comment]
`ES5` is a valid value as you can see in the [TS documentation](https://github.com/Microsoft/TypeScript/wiki/Compiler-Options)
The problem is the that the schema for tsconfig is too restrictive. I filed https://github.com/SchemaStore/schemastore/issues/79.

**Comment by aeschli** [comment]
resolved by #22
