### ISSUE TITLE
suggestion: add publisher in package.json

### ISSUE THREAD

**Issue by jfthuong** [microsoft/vscode-generator-code#200]
When generating the template for an extension (or at least for New Language Support), the attribute `publisher` is missing in **package.json**.

This results in the following error from `vsce` when trying to package / publish the extension:
```
ERROR  Missing publisher name. Learn more: https://code.visualstudio.com/...
```

For people who just start writing extensions, it is not every intuitive that you need to add `publisher` in the JSON file (especially since it is not documented anywhere).

Few solutions:
* Improve documentation to add it
* Make yeoman generates the field (either by populating with a blank value or by asking the name of the publisher when generating the extension)
* Improve message from `vsce` to indicate where to find the error

Note that several people had the issue apparently: https://github.com/microsoft/vscode-vsce/issues/368

Thanks

**Comment by aeschli** [comment]
That's actually done on purpose. We used to have a prompt for a publisher in there but we found it too distracting for new users. Only few extensions eventually get published and we found it better to start talking about the publisher when you are ready to do so, in vsce.
I support your request to improve the error message in vsce: https://github.com/microsoft/vscode-vsce/issues/368
Maybe vsce can even prompt you for a publisher (or suggest the logged-in user) and update your package.json
