### ISSUE TITLE
Add a generator for a (complex) webview extension (e.g. a custom editor)

### ISSUE THREAD

**Issue by iliazeus** [microsoft/vscode-generator-code#201]
Complex webviews often need to have their own dependencies and their own compile step. Right now, it can be hard to set it up properly.

**Comment by aeschli** [comment]
For more complex setups we have samples, e.g. https://github.com/microsoft/vscode-extension-samples/tree/master/webview-sample

**Comment by aeschli** [comment]
Closing as samples are better for that.
