### ISSUE TITLE
Do not ask to initialize a Git repository when already in one

### ISSUE THREAD

**Issue by TomasHubelbauer** [microsoft/vscode-generator-code#204]
My workflow when creating a new VS Code extension is to go to GitHub, create an empty repository for it, clone it and then run `npx yo code` in the repository directory and follow the generator.

The generator will create the extension in a directory named after the extension's identifier, not directly in the current directory, but the current directory is still already a Git repository, so perhaps the generator could be made to recognize this (either shell out to Git to ask or look for `.git` up the path - but this will not find repositories with differently named `.git`, which might be acceptable as I don't believe it to be at all common).

This question is redundant in case the directory being made for the extension is already in a repository directory so I believe skipping this question in that case would be a nice improvement to developer productivity and experience. Granted, it's a little thing, but little things add up and all that.

Let me know what you think of this proposal, thank you!

**Comment by TomasHubelbauer** [comment]
Do, however, generate a `.gitignore` with `node_modules` in it in the case an existing Git repository is detected would be another adjustment to this feature that I'd propose.

**Comment by aeschli** [comment]
I think that's too much smartness. What if there's a `.git` repo up the chain but I still want to init a git repo and have the other git files? Maybe we can skip it if the new folder already exists and has a `.git` folder. But also then we would need to know what to do with the other git files.
I'd rather keep the existing prompt in there.
