### ISSUE TITLE
VS Code types v1.45 are generated but the latest live version is 1.44

### ISSUE THREAD

**Issue by TomasHubelbauer** [microsoft/vscode-generator-code#205]
At the time of writing this issue, the VS Code extension Yeoman generator generates a `package.json` file which asks for `@types/vscode` at version 1.45, but the latest live version is 1.44:

https://www.npmjs.com/package/@types/vscode

Changing the version to 1.44 resolves the issue. It needs to be done in both `dependencies` and `devDependencies`.

**Comment by aeschli** [comment]
Sorry for that, I updated the extension a few days too early. In the meantime @types/vscode@1.45.1 is out
