### ISSUE TITLE
Yo Code for visual studio code extension generator is borken

### ISSUE THREAD

**Issue by JalpeshVadgama** [microsoft/vscode-generator-code#208]
- VSCode Version: 1.46-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Install the yo generator from the document yo generator global install command 
2. Try to create a code snippet extension for the visual studio code.
3.  It will ask several questions 
4. Here when you answer the language id question it's giving error like snippets not defined.

The following is a screenshot of that.
![image](https://user-images.githubusercontent.com/5141580/83352308-202d7e00-a368-11ea-8a71-5efdfb50e3e7.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
There was an error message on the first line.
The bug was to not stop there.

**Comment by JalpeshVadgama** [comment]
@aeschli - It's not generating files after this error? So what is the work around this?

**Comment by JalpeshVadgama** [comment]
@aeschli - Please advise what's needs to be done?

**Comment by JalpeshVadgama** [comment]
Hello team. I have been waiting for this for quite a long time? If anybody guide me on this?
