### ISSUE TITLE
Yo code command gives error

### ISSUE THREAD

**Issue by manojmkv** [microsoft/vscode-generator-code#209]
- VSCode Version: 1.45.1
- OS Version: Windows 10

Steps to Reproduce:

1. After running npm install -g yo generator-code when I run second command: Yo code then it returns me below error:

C:\development\ScriptMigration\VSCodeExtension>yo code

     _-----_     ╭──────────────────────────╮
    |       |    │   Welcome to the Visual  │
    |--(o)--|    │   Studio Code Extension  │
   `---------´   │        generator!        │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

Error: Promise rejected with value: {
  responseText: 'Unable to connect to https://vscode-update.azurewebsites.net/api/releases/stable. Error: unable to get local issuer certificate',
  status: 404
}
    at C:\Users\vermam\AppData\Roaming\npm\node_modules\yo\node_modules\loud-rejection\index.js:27:12
    at Array.forEach (<anonymous>)
    at EventEmitter.<anonymous> (C:\Users\vermam\AppData\Roaming\npm\node_modules\yo\node_modules\loud-rejection\index.js:23:24)
    at EventEmitter.emit (events.js:311:20)
    at EventEmitter.emit (domain.js:482:12)
    at emit (C:\Users\vermam\AppData\Roaming\npm\node_modules\yo\node_modules\signal-exit\index.js:78:11)
    at processEmit [as emit] (C:\Users\vermam\AppData\Roaming\npm\node_modules\yo\node_modules\signal-exit\index.js:156:5)
    at process.topLevelDomainCallback (domain.js:137:15)

Does this issue occur when all extensions are disabled?: Yes/No: I dint check this.

**Comment by manojmkv** [comment]
hello.. can I expect a response ?

**Comment by PrabhakarKalaiselvan** [comment]
I too had the same issue when I connected to a VPN. After disconnecting from the VPN, it worked.

**Comment by PrabhakarKalaiselvan** [comment]
I too face the same issue

**Comment by aeschli** [comment]
You are behind a proxy and need to set the `HTTP_PROXY` and `HTTPS_PROXY` environment variables.

`Yo code` should not terminate when it can't detect the latest VSCode version, but continue with a fallback.
I'll push a fix.
