### ISSUE TITLE
Can not install generator on windows 10

### ISSUE THREAD

**Issue by aminroosta** [Microsoft/vscode-generator-code#21]
Hi,

I get the following errors while trying to install the generator with `npm install -g generator-code`

![capture](https://cloud.githubusercontent.com/assets/2920178/12071286/4661684e-b0b9-11e5-88ae-cfa3246ecd1e.PNG)

**Comment by bpasero** [comment]
I cannot reproduce on Windows 10, just tried. I ran "npm install --g generator-code" from my home directory logged in as normal user.

**Comment by aminroosta** [comment]
@bpasero thank you,
is there a log file or something i could send you?

And which version od npm is working for you, i could try that version.

Thanks.

**Comment by bpasero** [comment]
@aminroosta 2.14.7

**Comment by wholroyd** [comment]
@aminroosta I had weird issues with the generator myself this weekend, but resolved them by upgrading npm itself and attempting the generator install a second time. I'm at npm version 3.5.2 as a result.

```
npm remove -g generator-code
npm install -g npm
npm install -g generator-code
```
