### ISSUE TITLE
Suggestion: Add a unit test template

### ISSUE THREAD

**Issue by hoddy3190** [microsoft/vscode-generator-code#211]
Currently the generated code only has a template for integration tests using vscode-test. I would like you to add a unit test template (without using vecode-test) as well.
When we add some unit tests to the current code template, we need to arrange code and directories, it's a little bit hard.

**Comment by aeschli** [comment]
I think we should leave that up to users.
- We don't want to add any additional prompts (Do you want a unit test template?)
- There are different test frameworks and flavors
