### ISSUE TITLE
Remove `--info-verbosity verbose` from webpack command line

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode-generator-code#231]
Prior to Webpack 5, `--info-verbosity verbose` was needed for proper problem matcher support, but that option no longer exists (and is thankfully unneeded for problem matcher support).

With that flag, Webpack will die with the following:
```
[webpack-cli] Unknown argument: --info-verbosity
```

This also completely breaks the `F5` ability -- as the build will fail.

**Comment by ilbrando** [comment]
Was this the feature which displayed that webpack was beginning compilation and that it has finished? I found that very useful because it made it easy to see when a new output was ready. Is it possible to re-introduce showing this information again?
