### ISSUE TITLE
Why do we specify `--devtool nosources-source-map` on the webpack command line?

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode-generator-code#232]
We specify `--devtool nosources-source-map` in the `package.json` scripts, but specify `devtool: 'source-map',` in the webpack.config.js.

I don't think we should be overwriting the `devtool: 'source-map',` value on the command line.

**Comment by aeschli** [comment]
Yes, something went wrong there..
I think the original idea was to not ship source maps in the published extension. For that we currently exclude `*.map` in `.vsceignore`.
So the fix would be to remove `devtool: 'source-map',` from the webpack config file. Then the `--devtool nosources-source-map` make sense again. Or we do `devtool: 'nosources-source-map' and add a parameter to package.

@eamodio  What do you think about source maps in the published extension?

**Comment by aeschli** [comment]
I kept `devtool: 'source-map'` (in fact `devtool: 'nosource-source-map'`) and use `--devtools hidden-source-map` for production

**Comment by eamodio** [comment]
I've verified that the above is the case.

@aeschli Why not just use `source-map` always?

**Comment by aeschli** [comment]
`source-map` also inlines the source in the source-map which is not really necessary.

**Comment by eamodio** [comment]
But that limits the ability of user's to be able to debug a running extension (although actually getting that to work is sometimes challenging). I would think that because most extensions are open-source, it would be nice for them to have source-maps enabled to allow for better production debugging (its what I use for GitLens and others)
