### ISSUE TITLE
Webpack config is non-standard

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode-generator-code#233]
Why do we have a `build/node-extension.webpack.config.js` file, rather than just a standard `webpack.config.js` file at the root? Then we avoid needing to specify the `--config` command line when calling webpack, and is a more standard setup.

**Comment by aeschli** [comment]
It's because we also support web extensions (when doing `yo code --insiders`).
Where you get the `build/web-extension.webpack.config.js`.

I thought it would be nicer to have them together and in the same folder.

**Comment by eamodio** [comment]
Since the `node-extension` is the default, I feel like we should keep that one as `webpack.config.js` and then have a specific version for the web. And I feel like just having them at the root is better as that will be more standard and not require command line flags for the "normal" case.
