### ISSUE TITLE
Remove `devtoolModuleFilenameTemplate` from webpack.config.js -- I don't think it is needed anymore

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode-generator-code#234]
I don't think `devtoolModuleFilenameTemplate` needs to be specified anymore, so we can remove this property

https://github.com/microsoft/vscode-generator-code/blob/31a8bcab1f470f749e91f7a3a81d0569945d937f/generators/app/templates/ext-command-ts/build/node-extension.webpack.config.js#L18

cc @connor4312

**Comment by connor4312** [comment]
If debugging still works, that lgtm

**Comment by eamodio** [comment]
Yeah, I haven't seen any issues without it.
