### ISSUE TITLE
autoClosingPairs and surroundingPairs properties don't match Monaco's IAutoClosingPair interface

### ISSUE THREAD

**Issue by ncardeli** [microsoft/vscode-generator-code#236]
When generating a language support extension, the language configuration file (`language-configuration.json`) has two properties whose values don't match the [LanguageSupport interface ](https://github.com/microsoft/vscode/blob/29bc5baadc95a797cc0df8cc8e66cea3cd289e34/src/vs/editor/common/modes/languageConfiguration.ts#L26) defined by Monaco. These properties are `autoClosingPairs` and `surroundingPairs`. Currently, they are defined like this:

```js
    // symbols that are auto closed when typing
    "autoClosingPairs": [
        ["{", "}"],
        ["[", "]"],
        ["(", ")"],
        ["\"", "\""],
        ["'", "'"]
    ],
    // symbols that can be used to surround a selection
    "surroundingPairs": [
        ["{", "}"],
        ["[", "]"],
        ["(", ")"],
        ["\"", "\""],
        ["'", "'"]
    ]
```

However, according to the `LanguageSupport` interface, these properties values should match the `IAutoClosingPair` and should be defined as:

```js
  // symbols that are auto closed when typing
  "autoClosingPairs": [
    {
      "open": "{",
      "close": "}"
    },
    {
      "open": "[",
      "close": "]"
    },
    {
      "open": "(",
      "close": ")"
    },
    {
      "open": "\"",
      "close": "\""
    },
    {
      "open": "'",
      "close": "'"
    }
  ],
  // symbols that can be used to surround a selection
  "surroundingPairs": [
    {
      "open": "{",
      "close": "}"
    },
    {
      "open": "[",
      "close": "]"
    },
    {
      "open": "(",
      "close": ")"
    },
    {
      "open": "\"",
      "close": "\""
    },
    {
      "open": "'",
      "close": "'"
    }
  ]
```

**Comment by ncardeli** [comment]
Thanks for taking a look at this!

I'm sorry, I'm far from an expert on these subjects, but I'm a little confused about two things:

1. At least for the `autoClosingPairs` property, the documentation you shared shows an example that matches the `IAutoClosingPair` interface.
2. The logic that reads the language configuration only considers the `open` and `close` properties: https://github.com/microsoft/vscode/blob/8af387dddd74950f16fbb2171d6d096fb23d7ce3/src/vs/editor/common/modes/languageConfiguration.ts#L263

**Comment by aeschli** [comment]
1. I'll update the documentation
2. The code that reads and converts the `language-configuration.json` file is here: https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/codeEditor/browser/languageConfigurationExtensionPoint.ts#L172
