### ISSUE TITLE
Use yo code to generate a template，and use "Bundle the source code with webpack". when press F5 , it still building,can not launch a extensionHost

### ISSUE THREAD

**Issue by KingJch** [microsoft/vscode-generator-code#239]

**Comment by barik** [comment]
More precisely, within vscode when doing `Run Extension` it executes:

```
yarn run v1.22.5
warning package.json: No license field
$ webpack --watch --config ./build/node-extension.webpack.config.js
asset extension.js 2.92 KiB [compared for emit] (name: main) 1 related asset
./src/extension.ts 1.43 KiB [built] [code generated]
external "vscode" 42 bytes [built] [code generated]
webpack 5.15.0 compiled successfully in 1836 ms
```
but then does not actually open the VS Code Extension Development Host.

**Comment by barik** [comment]
Should it be `npm:test-compile` in `launch.json` for `"preLaunchTask"`?

**Comment by tomchen** [comment]
Yeah. Same problem here.

I guess [tsl-problem-matcher](https://github.com/eamodio/vscode-tsl-problem-matcher) is incompatible with webpack 5.

As a temporary solution, you could:

in .vscode/tasks.json, change

```json
"problemMatcher": [
	"$ts-webpack-watch",
	"$tslint-webpack-watch"
],
```

to

```json
"problemMatcher": "$tsc-watch",
```

in package.json, change

```json
"watch": "webpack --watch --config ./build/node-extension.webpack.config.js",
```

to

```json
"watch": "tsc -watch -p ./",
```

Now the scripts `watch` and `test-watch` do exactly the same thing. So, if you want, you could also get rid of one of them completely and use the other one.

**Comment by aeschli** [comment]
I see the same.
Webpack finishes with message:
`webpack 5.18.0 compiled successfully in 1619 ms`

@eamodio Can you help by updating the extension? PR https://github.com/eamodio/vscode-tsl-problem-matcher/pull/5 is there but it seem the pattern needs to be improved further

**Comment by eamodio** [comment]
I've been holding off on further updates because of this discussion https://github.com/webpack/webpack-cli/issues/2374. But I'll see what I can do with the messages we have now.

**Comment by FuPeiJiang** [comment]
for the time being, use webpack-cli@4.2.0
or
in `node-extension.webpack.config.js`
```
  infrastructureLogging: {
    level: 'log',
  },
```

refs: https://github.com/webpack/webpack-cli/pull/2206#issuecomment-752932074
https://webpack.js.org/configuration/other-options/#infrastructurelogging

**Comment by aeschli** [comment]
@eamodio Any updates? I can't leave it broken...

**Comment by eamodio** [comment]
Will get it fixed today, though with weback cli later than 4.2 you'll need a flag (until I can get changes landed)

**Comment by eamodio** [comment]
@aeschli I published a new version of the problem matchers (0.4.0). Although with webpack-cli > 4.2 we'll need to add this to the `webpack.config.js` to get it work properly.

```json
 infrastructureLogging: {
    level: 'log',
  },`
```

Although, even with that change, I see the problem matcher match error, but I am not seeing `F5` being blocked. But I don't think that is because of the matcher -- I feel like it has to do with the terminal changes & tasks.

**Comment by aeschli** [comment]
Thanks @eamodio, the new version works!

**Comment by felipecrs** [comment]
> Although, even with that change, I see the problem matcher match error, but I am not seeing F5 being blocked. But I don't think that is because of the matcher -- I feel like it has to do with the terminal changes & tasks.

@eamodio I believe https://github.com/eamodio/vscode-tsl-problem-matcher/pull/9 solves this issue.
