### ISSUE TITLE
preLaunchTask causes infinite loading when trying to debug

### ISSUE THREAD

**Issue by AndrisJefimovs** [microsoft/vscode-generator-code#244]
Two days ago I created an extension using the command `yo code` with following options
+ Typescript
+ Git repo
+ Webpack enabled

An extension I created today has the same setup. The only difference was that if pressing *Debug* webpack finishes building and then VS Code is loading infinitely. I reinstalled VS Code and tried different versions, later I took a look if there are any changes in the files.

In the new `launch.json` file I noticed one new line : `"preLaunchTask": "${defaultBuildTask}"`. I didn't find it in the old one and by removing it everything works fine and the Development Host starts successfully.

Hopefully it is the right place to post. :)

**Comment by aeschli** [comment]
This should be fixed now.
- Make sure you have version 0.4.0 of the `TypeScript + Webpack Problem Matchers` extension.
- No need to rerun the generator. You can add `"preLaunchTask": "${defaultBuildTask}"` back.
- Make sure the tasks file has
```
		{
			"type": "npm",
			"script": "watch",
			"problemMatcher": [
                "$ts-webpack-watch",
                "$tslint-webpack-watch"
			],
			"isBackground": true,
			"presentation": {
				"reveal": "never"
			},
			"group": {
				"kind": "build",
				"isDefault": true
			}
		},
```
- Press F5 to launch. In the debug console you should see that webpack runs and ends with something like `webpack 5.24.2 compiled successfully in 1459 ms`. That will be detected and the launch will continue
