### ISSUE TITLE
Cant create extension? Command 'Hello World' resulted in an error (command 'demo.helloWorld' not found)

### ISSUE THREAD

**Issue by Radical-Dave** [microsoft/vscode-generator-code#247]
- VS Code Version:
- OS Version:

Steps to Reproduce:

1. yo code (Demo,demo, demo, y, y, npm)
2. cd demo, code .
3. F5, Command Palette, Hello World.. results:

Command 'Hello World' resulted in an error (command 'demo.helloWorld' not found)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Radical-Dave** [comment]
Latest of all. 20H2.

**Comment by Jat-coder** [comment]
Apparantly, this problem arises due to some other extension that is active in vscode at the time, if you disable all the extensions and restart the vscode the problem subsides.

**Comment by aeschli** [comment]
I'm not able to reproduce. Yes, other faulty extensions can cause if they crash.
