### ISSUE TITLE
Move ./src/test to ./test

### ISSUE THREAD

**Issue by felipecrs** [microsoft/vscode-generator-code#259]
This allows the code to be better organized, because inside `src` multiple folders can exist such as `model`. `view`, `controller`, and does not make sense to have them beside `test`.

Before:

```
.
├── src
│   ├── common
│   ├── controller.ts
│   ├── extension.ts
│   ├── files
│   ├── gerrit
│   ├── git
│   ├── test
│   └── view
├── tsconfig.json
```

After:

```
.
├── src
│   ├── common
│   ├── controller.ts
│   ├── extension.ts
│   ├── files
│   ├── gerrit
│   ├── git
│   └── view
├── test
├── tsconfig.json
```

Projects scaffolded by `nest` have such structure.

Some changes will be required in the `tsconfig.json` to accommodate this change.

**Comment by aeschli** [comment]
How would the import in the test files look like?

**Comment by felipecrs** [comment]
As in Nest's example:

```ts
import { AppModule } from '../src/app.module';
```

**Comment by aeschli** [comment]
Having a `src` in the imports is not very nice (IMO).

No plans to change the location...
