### ISSUE TITLE
Remove **/*.map from .vscodeignore when using webpack

### ISSUE THREAD

**Issue by felipecrs** [microsoft/vscode-generator-code#261]
Otherwise it's pointless to have `--devtool hidden-source-map` in the `"package": "webpack --mode production --devtool hidden-source-map"`.

**Comment by aeschli** [comment]
Not sure I understand.

The idea is to not publish source maps. `--devtool hidden-source-map` allows that as it prevents that webpack adds a reference to the map file.

**Comment by felipecrs** [comment]
Actually, the problem is that during development the `*.map` files get created, but when calling with `--devtool hidden-source-map` these `*.map` does not get automatically deleted, which could cause the `*.map` files to accidentally be packaged in the extension.
