### ISSUE TITLE
Theme tests timesout often

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode-generator-code#276]
The theme tests timesout every time on the first build but on a re-run it's fine.

Seeing this:
```
1) test code generator
       theme import:
     Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/tanha/Documents/GitHub/msft-vscode-generator-code/test/test.js)
      at listOnTimeout (node:internal/timers:556:17)
      at processTimers (node:internal/timers:499:7)
```

**Comment by aeschli** [comment]
The tests fetch a theme file from `http://www.monokai.nl/blog/wp-content/asdev/Monokai.tmTheme`.
This seems to work for me, I don't see the time out. But we could change this to a local URL.

**Comment by aeschli** [comment]
Remove the test. We have another test that tests loading from a file.
