### ISSUE TITLE
Why noLib in tsconfig.json?

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode-generator-code#28]
I do notice some default function such as `console` is still available:
![image](https://cloud.githubusercontent.com/assets/3254987/12694136/87498c86-c6d7-11e5-9c0b-3f7a9868a1f1.png)

This make it harder to write extension?

**Comment by bpasero** [comment]
Because we want to control 100% the environment, e.g. otherwise you would get "window." suggestions although there is no DOM in extensions.

**Comment by unional** [comment]
This cause weird things on intellisense such as missing array, treating it as object:

![image](https://cloud.githubusercontent.com/assets/3254987/12694173/dec7c094-c6d8-11e5-8f29-a89dd89c51c9.png)

**Comment by unional** [comment]
So may be including a subset of `lib.d.ts` would be the solution?

**Comment by bpasero** [comment]
Not for me, what typescript version are you using?

![image](https://cloud.githubusercontent.com/assets/900690/12694182/02016bf4-c725-11e5-9d83-eb1909031ffe.png)

**Comment by unional** [comment]
I have two instances of vscode running side by side, one with `noLib` and one without. The normal one works fine.
The extension one using 1.7.5 within the `node_modules`, the normal one using 1.8.0

**Comment by bpasero** [comment]
@unional can you upload the one where it does not work as zip somewhere for me to try? are you using vscode 0.10.6?

**Comment by unional** [comment]
I'm doing a diff. I `yo code` another one and it seems to be working. Will let you know.

**Comment by unional** [comment]
[vscode-project-manager.zip](https://github.com/Microsoft/vscode-generator-code/files/110701/vscode-project-manager.zip)

Couldn't figure out why. Remove most differences and redo `npm i` and the issue still persist.

Your help is much appreciated.

Thanks.

**Comment by unional** [comment]
Yes, using vscode 0.10.6

**Comment by unional** [comment]
Sorry that the code `extension.ts` has some obvious error in it. I was in the middle of writing it and encounter this issue.

I was trying to simply do `context.globalState.get<any[]>` (or context.globalState.get<projectEntry[]>` when I encounter this issue.

**Comment by bpasero** [comment]
So it works when you fix those errors?

**Comment by unional** [comment]
No, the error still persist. It's unrelated
