### ISSUE TITLE
Update to `yeoman-generator` 5

### ISSUE THREAD

**Issue by Logicer16** [microsoft/vscode-generator-code#285]
`yeoman-generator@5` was released in February of this year and is no long dependant on packages with dependancies of deprecated packages [`urix`](https://github.com/lydell/urix#deprecated)and [`resolve-url`](https://github.com/lydell/resolve-url#deprecated). These are currently the only deprecated packages depended on by this project and will remove the depreciation warnings when installing/updating this project.

**Comment by bpasero** [comment]
👏
