### ISSUE TITLE
Possible wrong instruction in `vsc-extension-quickstart.md`

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode-generator-code#287]
> ...
> [You can also reload (_Ctrl+R or Cmd+R on Mac_) the VS Code window with your extension to load your changes.](https://github.com/microsoft/vscode-generator-code/blob/main/generators/app/templates/ext-command-js/vsc-extension-quickstart.md#make-changes)

Isn't `Ctrl+R or Cmd+R on Mac` bound to `workbench.action.openRecent`? How to use that to reload VSCode window? I guess the manual meant `workbench.action.reloadWindow`?

**Comment by aeschli** [comment]
When in a `[Extension Development Host]` window, `Cmd + R` reloads the window. I just verified that

**Comment by wenfangdu** [comment]
@aeschli I see, I just realized that I changed the shortcut for `workbench.action.reloadWindow`, hence, the confusion.
