### ISSUE TITLE
can not run generator on yo 3.1.1

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-generator-code#290]
When run `yo code`, I got 

```
This generator (code:app) requires yeoman-environment at least 3.0.0, current version is 2.10.3, try reinstalling latest version of 'yo' or use '--ignore-version-check' option
```

but `yo --version` is `3.1.1`

**Comment by aeschli** [comment]
Did it help updating `yo`? (`npm i -g yo`). If not, please file an issue against https://github.com/yeoman/yo/issues

We need `yo` version 4 now. It's built on `yeoman-environment: 3`.
