### ISSUE TITLE
Improvements to Adding Web Bits generator

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode-generator-code#292]
- Generates an incorrect extension dependency "v@vscode/test-web": "^0.0.6". Removing the leading "v" fixed the problem.
- Add a launch.json entry for running the extension as a web extension in VS Code. This also requires adding a corresponding task in tasks.json
- Add .vscode-test-web to `.gitignore``

**Comment by aeschli** [comment]
Closing as I've removed the `add web bits' generator
