### ISSUE TITLE
Extension fails to run with error: Could not find the task '${defaultBuildTask}'.\

### ISSUE THREAD

**Issue by trafnar** [microsoft/vscode-generator-code#298]
I'm following the instructions for building an extension [here](https://code.visualstudio.com/api/get-started/your-first-extension).

When I press`f5` in order to run the extension, I'm presented with an error:
`Could not find the task '${defaultBuildTask}'.`
If I click "debug anyways" I get the error:
`Configured debug type 'pwa-extensionHost' is not supported.`
If I then click "Install pwa-extensionHost Extension` the extension marketplace returns no search results. 

I'm not sure what these error messages mean, I'd appreciate any help.

I'm using vscode Version: 1.59.1

**Comment by aeschli** [comment]
@connor4312 Any idea how that can happen?

**Comment by connor4312** [comment]
You probably disabled js-debug at some point. Please reenable it. (Can be found by looking for `@builtin` in the extension search)

**Comment by misolori** [comment]
I also encountered this today:

<img width="1020" alt="CleanShot 2021-09-28 at 10 01 56@2x" src="https://user-images.githubusercontent.com/35271042/135132707-a41676dd-4720-4905-9d46-13f4ce7124f0.png">

And I did disable the `JavaScript Debugger` ext because I had the nightly one installed. Does that mean that nightly version is not compatible?

**Comment by misolori** [comment]
Actually, I disabled nightly and enabled the regular one and am still hitting this. Only happens on the first try and subsequent tries work fine:

https://user-images.githubusercontent.com/35271042/135133876-c16bea31-a403-48ce-9de7-e4feeaa4ddef.mp4

**Comment by connor4312** [comment]
The "task cannot be tracked" error is not related to this issue or the js debugger

**Comment by connor4312** [comment]
Also, I notice the user as on 1.59, not the latest 1.60 version where we remove the old debuggers. I can't repro this problem and I suspect it doesn't happen anymore now that the debugger story is simplified. Please let me know if someone hits this again.

**Comment by misolori** [comment]
File https://github.com/microsoft/vscode/issues/134054 to track it in core. I though this was related to generator.

**Comment by tooilxui** [comment]
> You probably disabled js-debug at some point. Please reenable it. (Can be found by looking for `@builtin` in the extension search)

This actually helps me a lot. When I enable js-debug (Microsoft JavaScript debugger) and restart the vscode window, everything works fine.

![image](https://github.com/microsoft/vscode-generator-code/assets/36430858/5bcc9a5f-3c29-4883-9581-69bd3719229c)
