### ISSUE TITLE
Tests for `webpack`ed generator are not valid

### ISSUE THREAD

**Issue by felipecrs** [microsoft/vscode-generator-code#299]
1. The tests included in the `webpack`ed generator does not really test if the extension gets activated
2. It succeeds currently, because the extension does not get activated at all
3. If we try to activate the extension (which everyone will do for running their own tests), it fails, because no `./dist/extension.js` can be found (as in such case, the file is at `./out/extension.js`).

**Comment by felipecrs** [comment]
`snowpack` and its handy `test` mode is a good option, as long as https://github.com/snowpackjs/snowpack/issues/3718 gets fixed.

**Comment by aeschli** [comment]
Thanks! There's a missing `npm run compile` in `pretest`.

Fixed by https://github.com/microsoft/vscode-generator-code/commit/c48bd68b1bca224c264b70d154f51c5a94d80436

**Comment by felipecrs** [comment]
What about:

https://github.com/microsoft/vscode-generator-code/blob/main/generators/app/templates/ext-command-ts/vscode-webpack/vscode/tasks.json#L22-L32

https://github.com/microsoft/vscode-generator-code/blob/main/generators/app/templates/ext-command-ts/vscode-webpack/vscode/launch.json#L31

?

**Comment by aeschli** [comment]
Thanks, I pushed another changeset.
