### ISSUE TITLE
Unable to run extension due to @types/vscode version difference

### ISSUE THREAD

**Issue by bkrmadtya** [microsoft/vscode-generator-code#314]
Hello everyone,
This is my first time trying out vscode extension. I tried following the guide here https://code.visualstudio.com/api/get-started/your-first-extension

The version for `@types/vscode` version is `^1.62.0` in the generated `package.json`. However, the latest version available for it is just `1.61.0`. I have tried it with both npm and yarn.
![image](https://user-images.githubusercontent.com/39879795/140421699-ee3b6d48-bf27-4b3e-a240-b52cf8b9d41d.png)

I tried with the `1.61.0` version but I couldn't run the extension due to incompatible version of `@types/vscode`.
![image](https://user-images.githubusercontent.com/39879795/140421260-2e18033d-48e1-48db-8d91-a42bf8c17441.png)

Hope to get some guidance. Thank you in advance.

**Comment by Romaleks360** [comment]
I'm having the same problem. How did you fix it?

**Comment by bkrmadtya** [comment]
> I'm having the same problem. How did you fix it?

I updated the vscode to latest version and that fixed it.

**Comment by bkrmadtya** [comment]
> > I'm having the same problem. How did you fix it?
> 
> I updated the vscode to latest version and that fixed it.

And also downgraded the version of `@types/vscode` to `1.61.0`. Hope that solves your issue.

**Comment by justinmcp** [comment]
@Romaleks360 @bkrmadtya @types/vscode has been updated.
