### ISSUE TITLE
Generated language extension is not working

### ISSUE THREAD

**Issue by godstanis** [microsoft/vscode-generator-code#316]
Here is my input for `yo code` command:

```
? What type of extension do you want to create? New Language Support
? URL or file to import, or none for new:
? What's the name of your extension? Example language description
? What's the identifier of your extension? example-scripting-language-support
? What's the description of your extension? Description here
Enter the id of the language. The id is an identifier and is single, lower-case name such as 'php', 'javascript'
? Language id: exmpl
Enter the name of the language. The name will be shown in the VS Code editor mode selector.
? Language name: Example Language
Enter the file extensions of the language. Use commas to separate multiple entries (e.g. .ruby, .rb)
? File extensions: .exmpl
Enter the root scope name of the grammar (e.g. source.ruby)
? Scope names: source.exmpl
? Initialize a git repository? No
```

Then I press F5, create a new file "test.exmpl" with some comments, vscode detects the file as "exmpl", but there is no highlighting and the file is still being shown as plain white text. No errors in debug console, only this deprecation warning:

```sh
(node:18368) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)
```

Am I doing something completely wrong? Or am I missing something here?

**Comment by aeschli** [comment]
Check out the generated grammar at `syntaxes/example-scripting-language-support.tmLanguage.json`

It's for illustration and only contains rules for string literals ("adasd") and keywords (`if`).

![image](https://user-images.githubusercontent.com/6461412/144904919-93b647e8-8130-47c2-b8b9-d74531da3f0c.png)

Use the `Developer: Inspect Editor Tokens and Scopes` command to see what scopes are generated and how they are themed.
