### ISSUE TITLE
tsconfig.json confusing settings

### ISSUE THREAD

**Issue by memeplex** [microsoft/vscode-generator-code#323]
The compilar configuration includes both:

```json
	"exclude": [
		"node_modules",
		".vscode-test"
	]
```

and

```json
	"compilerOptions": {
		"rootDir": "src",
```

According to the documentation [exclude](https://www.typescriptlang.org/tsconfig#exclude):

> Specifies an array of filenames or patterns that should be skipped when resolving include. Important: exclude only changes which files are included as a result of the include setting. 

And regarding [rootDir](https://www.typescriptlang.org/tsconfig#rootDir):

> Note that TypeScript will never write an output file to a directory outside of outDir, and will never skip emitting a file. For this reason, rootDir also enforces that all files which need to be emitted are underneath the rootDir path.

So it seems that the `exclude` setting may be both ineffective (because there is no `include`) and redundant (because `rootDir` is already enforcing that all emitted files are underneath `src`).

**Comment by aeschli** [comment]
I think you are correct, you can delete the exclude section.
