### ISSUE TITLE
The 1 extension(s) below, in workspace recommendations have issues: eamodio.tsl-problem-matcher

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-generator-code#326]
The 1 extension(s) below, in workspace recommendations have issues: eamodio.tsl-problem-matcher (not found in marketplace)

Came from setting up a standard ts project. 

![image](https://user-images.githubusercontent.com/8586769/149070993-2fd9badb-1b34-4363-ae6b-e68e62061d44.png)

Looks like the new id has no `e` prefix?

cc @eamodio did this change?

![image](https://user-images.githubusercontent.com/8586769/149071091-e75c861d-ed37-4ce8-bcbd-e0d824caa708.png)

**Comment by aeschli** [comment]
`amodio.tsl-problem-matcher` is the new extension name.
The latest version of the generator uses the new name, but your project probably still refers to the old name.

**Comment by cailijunijq** [comment]
配置出现了问题，删除.vscode文件夹即可
