### ISSUE TITLE
error while installing yo code generator

### ISSUE THREAD

**Issue by Alok-joseph** [microsoft/vscode-generator-code#330]
PS C:\Users\ALOK & AMOGH\Downloads\python projects> npm install -g yo generator-code
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be 
problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path C:\Users\ALOK & AMOGH\AppData\Roaming\npm\node_modules\yo
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c yodoctor
npm ERR! 'AMOGH\AppData\Roaming\npm\node_modules\yo\node_modules\.bin\' is not recognized as an internal or external command,
npm ERR! operable program or batch file.
npm ERR! node:internal/modules/cjs/loader:936
npm ERR!   throw err;
npm ERR!   ^
npm ERR! 
npm ERR! Error: Cannot find module 'C:\Users\yeoman-doctor\lib\cli.js'
npm ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
npm ERR!     at node:internal/main/run_main_module:17:47 {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: []
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ALOK & AMOGH\AppData\Local\npm-cache\_logs\2022-02-17T09_17_12_344Z-debug-0.log
PS C:\Users\ALOK & AMOGH\Downloads\python projects> 

i have been trying to install yo generator-code
but every time i tries it throws an error
please help

**Comment by aeschli** [comment]
This is a problem of `yo`. https://github.com/yeoman/yo/issues/128
