### ISSUE TITLE
15 vulnerabilities when installing yo and generator-code

### ISSUE THREAD

**Issue by KTSnowy** [microsoft/vscode-generator-code#333]
![Screenshot 2022-03-04 212921](https://user-images.githubusercontent.com/73310001/156859919-3b2cd31c-47e8-47be-8470-b4765ffa391d.png)

I know that the issue comes from yo, but it's concerning that there's still 15 vulnerabilities and 3 deprecated warnings after 3 months( #318 ).

**Comment by aeschli** [comment]
There's nothing we can do. I see you also pinged yo: https://github.com/yeoman/yo/issues/716

**Comment by KTSnowy** [comment]
@aeschli  We could temporarily fork Yo to fix the outdated dependencies, that's probably what's causing most of the vulnerabilities.
