### ISSUE TITLE
Cannot find module 'vscode' or its corresponding type declarations.ts(2307)

### ISSUE THREAD

**Issue by g8up** [microsoft/vscode-generator-code#338]
I execute `yo code` generate a project with webpack.

It has a error in `src/extensions.ts` :
```
Cannot find module 'vscode' or its corresponding type declarations.ts(2307)
```
As https://www.npmjs.com/package/vscode shows ,`vscode` package is deprecated. 

How to migrate it ?

**Comment by nhedger** [comment]
I just generated a fresh extension using the following settings.

- `New Extension (TypeScript)`
- `Bundle the source code with webpack? y`
- `Which package manager to use? npm`

Unfortunately, I'm unable to reproduce the error. 

Howeverm, I suspect that you may be missing the `@types/vscode` devDependency from your `package.json` file.

**Comment by g8up** [comment]
I switched yarn to npm, and `npm install` again. It was fixed.
thx! @nhedger
