### ISSUE TITLE
yo generator-code installation issues

### ISSUE THREAD

**Issue by BradTFT** [microsoft/vscode-generator-code#344]
Hi,

not sure if this is the right place to put this but i have been trying to install this package all day and no one has been able to find a solution.

i ran `npm init` and set everything up. when i go to run `npm install -g yo generator-code`, i get these errors after it finishes.

```
user:~/directory$ npm install -g yo generator-code
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

changed 898 packages, and audited 899 packages in 1m

64 packages are looking for funding
  run `npm fund` for details

7 vulnerabilities (5 moderate, 2 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
```

what is a fix for these issues.

**Comment by nhedger** [comment]
Hey @BradTFT,

Your issue looks similar to https://github.com/microsoft/vscode-generator-code/issues/341.

These are warning emitted because some of `yo`'s dependencies are outdated.

This shouldn't prevent you from generating a extension though.

**Comment by BradTFT** [comment]
Hi, @nhedger, 

How can i generate the extension if i cannot install the generator?
how can i fix the outdated dependancies

**Comment by nhedger** [comment]
> How can i generate the extension if i cannot install the generator?

Based on the log you provided, the installation should have worker correctly. Those are warnings and not errors.

After running `npm install -g yo generator-code`, you can check whether `yo` is available by running the following.

```
yo --version
```

> how can i fix the outdated dependancies

You cannot do it yourself. The maintainers of `yo` have to update the dependencies or their tool and the issue has already been reported in https://github.com/yeoman/yo/issues/716

**Comment by BradTFT** [comment]
My `yo --version` has returned `bash: yo: command not found`
i will attempt to fix the dependence in the provided link

**Comment by BradTFT** [comment]
also my package.json contains this 


```  },
  "homepage": "https://github.com/BradTFT/vscode-extension#readme",
  "dependencies": {
    "generator-code": "^1.6.9",
    "uuid": "^8.3.2",
    "yo": "^1.8.5"
  }
}

```

**Comment by aeschli** [comment]
It's a dup of #333. Yes, it's a pity that `yo` takes so long to update to dependencies. Regardless of the warnings, I think it's safe to use the generator.

Your package.json should not have any changes if you used the `-g` (global) parameter

**Comment by BradTFT** [comment]
so how am i supposed to fox this
