### ISSUE TITLE
Running extension gets error

### ISSUE THREAD

**Issue by BradTFT** [microsoft/vscode-generator-code#345]
Hi,

So i installed and went through the generator process and got started. updated vscode to the newest version, and followed the docs. I went into the F5 window and ran the Hello World command. after i ran it it did nothing but brought this popup up: 
```
Activating extension 'undefined_publisher.vscode-extension' failed: Cannot find module '/home/user/vscode-extension/vscode-extension/dist/extension.js' Require stack: - /usr/share/code/resources/app/out/vs/loader.js - /usr/share/code/resources/app/out/bootstrap-amd.js - /usr/share/code/resources/app/out/bootstrap-fork.js.
```
i read thru some other issues and have not found the fix for it.

**Comment by BradTFT** [comment]
@aeschli I apologize for the ping but no one has responded for close to 3 days

**Comment by aeschli** [comment]
Does `vscode-extension/dist/extension.js` exist? If not, did the build run? It should be part of the F5.
Is this with webpack? Did you install the recommended extensions?

**Comment by BradTFT** [comment]
Im not sure. Im running ts as my main file. the build ran but it just popped the error message up. the developer window was open and functioning. im not sure about the webpack and i belive all of the recommended extensions are installed

**Comment by BradTFT** [comment]
Hi,

I just found the dist dir and there is a file named diff.js. i added an extension.js file to it but i got the same errors

**Comment by BradTFT** [comment]
solved via https://github.com/microsoft/vscode/issues/148932
