### ISSUE TITLE
Add link to extension UX guidelines to generator CLI

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode-generator-code#352]
In an effort to get more eyes on the new [extension UX guidelines](https://code.visualstudio.com/api/ux-guidelines/overview)—and as a result, higher quality extensions—I think it could be useful to have a link to the guidelines directly in the CLI output once the extension has been created:

<img width="746" alt="CleanShot 2022-06-09 at 15 46 10@2x" src="https://user-images.githubusercontent.com/25163139/172957829-85a8b03c-a6cf-477a-97fe-6a9d28770e7e.png">

It would also be worth adding it to the quickstart file, perhaps in the "Go further" section:

https://github.com/microsoft/vscode-generator-code/blob/b13a22e1ec5d1f5aa92baa8a1dd2e3105c66f726/generators/app/templates/ext-command-web/vsc-extension-quickstart.md?plain=1#L39-L43

cc @hawkticehurst @misolori

**Comment by misolori** [comment]
I would definitely add it to the markdown file as that's where it will have the most visibility.

**Comment by aeschli** [comment]
We can add a link to vsc-extension-quickstart.md. Do you want to make a PR?

**Comment by hawkticehurst** [comment]
I'd be happy to make a PR for this
