### ISSUE TITLE
Template readmes include incorrect keyboard shortcut

### ISSUE THREAD

**Issue by hawkticehurst** [microsoft/vscode-generator-code#353]
In a handful of the extension templates, the READMEs include the following line:

> Press `Ctrl+Space` (Windows, Linux) or `Cmd+Space` (macOS) to see a list of Markdown snippets

On macOS, `Cmd+Space` triggers the Spotlight Search. Instead, `Ctrl+Space` is the correct shortcut to view Markdown snippets on macOS.

**Comment by daviddossett** [comment]
Go for it!
