### ISSUE TITLE
Do a consistency pass on extension templates

### ISSUE THREAD

**Issue by hawkticehurst** [microsoft/vscode-generator-code#359]
As I've been making some PRs recently I've noticed that there are minor inconsistencies across the various extension templates such as:

- Inconsistent capitalization (i.e. sometimes `CMD` is used and other times `Cmd` is used)
- Inconsistent usage of "VS Code" versus "VSCode" (I believe brand guidelines say it should always be "VS Code")
- Inconsistent usage of periods at the end of bullet list items
- Other bits and pieces

If addressing this sounds desirable, I would be happy to contribute a PR that does a pass on these types of things and generally adds some polish to the extension templates.

**Comment by hawkticehurst** [comment]
cc @daviddossett / @misolori

**Comment by misolori** [comment]
Definitely go for it, we get PRs for typo fixes all the time.
