### ISSUE TITLE
Missing files in the YO template?

### ISSUE THREAD

**Issue by parithon** [microsoft/vscode-generator-code#363]
When trying to create a new repository for a code extension I have run into the following error. Did we forget a file in the generator-code template?

![image](https://user-images.githubusercontent.com/8602418/181391001-7c347e8a-2df3-414b-996e-fd0756532968.png)
![image](https://user-images.githubusercontent.com/8602418/181391060-9f963f06-42ae-490b-9a49-08e3d9c3e9e1.png)
![image](https://user-images.githubusercontent.com/8602418/181391319-e4e84761-177d-4e12-b8d8-c57f3c160617.png)

**Comment by parithon** [comment]
I manually added the `.gitignore` file using the following [.gitignore](https://github.com/microsoft/vscode-generator-code/blob/a2a98571bd1f646a128f9a29c12ad7850aca8d64/generators/app/templates/ext-command-ts/.gitignore) file which allowed the generator to complete the job.

**Comment by AnuragVasanwala** [comment]
@parithon Thanks. I was facing same issue and adding `.gitignore` manually solved issue ✅

**Comment by kasajian** [comment]
Just to help with the prioritize this based on severity of this: this basically breaks the very first thing you do in the SDK docs @ "Your First Extension"
https://code.visualstudio.com/api/get-started/your-first-extension

**Comment by AnuragVasanwala** [comment]
@kasajian Yes, it breaks the very first tutorial: "[Your First Extension](https://code.visualstudio.com/api/get-started/your-first-extension)"

**Comment by danawoodman** [comment]
For those coming here from a Google search, as @parithon says, you need to add that file, so for me that looked like this:

```shell
code /Users/danawoodman/Library/pnpm/global/5/.pnpm/generator-code@1.6.13/node_modules/generator-code/generators/app/templates/ext-command-ts/.gitignore
```

Then paste in and save:

```gitignore
out
dist
node_modules
.vscode-test/
*.vsix
```

**Comment by shoffmeister** [comment]
For additional context, this occurs when the code generator is run _with defaults_ ("Initialize a git repositor (Y/n)"), so if one follows the official Microsoft "Your first extension" tutorial in an attempt to minimize friction and the barrier to entry - this is exactly when this hits.

**Comment by bpasero** [comment]
via `generator-code@1.6.14`
