### ISSUE TITLE
Generator produces dependency on non-existing dependency "@types/vscode": "^1.70.0"

### ISSUE THREAD

**Issue by shoffmeister** [microsoft/vscode-generator-code#365]
Following the official Microsoft tutorial at https://code.visualstudio.com/api/get-started/your-first-extension yields a `package.json` which, at the time of this writing (see submission timestamp), contains:

```
  "devDependencies": {
    "@types/vscode": "^1.70.0",
```
Trying an `npm install` with that fails _as I am writing this_.

Obviously 1.70.0 is my current (released) vscode version (auto-upgraded via the Microsoft rpm package repo), but there is no 1.70.0 type package at https://www.npmjs.com/package/@types/vscode _as I am writing this_

It seems as if there is a problem 
* either in the code generator, in that it is overly eager in making use of fresh versions, 
* or there is a problem in the vscode (product) release process, where new versions of the vscode types package are not released in time.

Note that as I am writing this, the npm repo has 1.69.1 as the latest version of the types - and I am aware of there having been an 1.69.2 release of vscode proper, so there is one more version inconsistency, and I cannot tell what is right or wrong.

In any event, running through the Microsoft tutorial for the first extension should produce code that is guaranteed to compile and run, i.e. all dependencies should resolve at all times (perhaps worthwhile adding some kind of CI for the generator with an E2E test, given how aggressively it tracks the vscode version?)

**Comment by shoffmeister** [comment]
Work-around: 1.70.0 -> 1.69.1 (and crank down the dependency on the engines too)

**Comment by bpasero** [comment]
The version is out now.
