### ISSUE TITLE
No matching version found for @types/vscode@^1.70.0 (New Extension template, TypeScript)

### ISSUE THREAD

**Issue by terotil** [microsoft/vscode-generator-code#368]
Following https://code.visualstudio.com/api/get-started/your-first-extension at the time of writing this ends up with `No matching version found for @types/vscode@^1.70.0` once you have first resolved #363.  Turns out the latest release of that package is 1.69.1.  Once you downgrade dep to that, `npm install` works.

**Comment by aeschli** [comment]
@types/vscode@1.70.0 is now available
