### ISSUE TITLE
Hello World example not working

### ISSUE THREAD

**Issue by scarf005** [microsoft/vscode-generator-code#375]
followed https://code.visualstudio.com/api/get-started/your-first-extension with pnpm and typescript, however command does not appears.

![image](https://user-images.githubusercontent.com/54838975/194740301-7a4fbae9-8e95-4855-83b0-3ca5f4f0e1b7.png)

```
Version: 1.71.2
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:12:14.256Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.0-48-generic
Sandboxed: No
```

**Comment by harupy** [comment]
@scarf005 I encountered the same issue.

```diff
{
  "name": "vscode-mlflow",
  "displayName": "vscode-mlflow",
  "description": "VSCode extension for MLflow",
  "version": "0.0.1",
	"publisher": "vscode-mlflow",
  "engines": {
+    "vscode": "^1.72.0"
-    "vscode": "^1.71.0"
  },
```

fixed the issue.

**Comment by harupy** [comment]
I think upgrading VSCode to 1.72 should also fix the issue.

**Comment by scarf005** [comment]
yes, it solved the issue. still, the documentation for version is somewhat lacking in my opinion.

**Comment by dantehemerson** [comment]
I'm still having this issue with vscode 1.72  engine.

**Comment by EvilJoker** [comment]
i meet it again. but vscode is  1.80.0.
the value of  package.json by yo code  building project  is "vscode":"^1.88.0".

i try to downward the version of package.json to 1.80.0. it solved
