### ISSUE TITLE
helloworld command: no matching commands

### ISSUE THREAD

**Issue by luca1226** [microsoft/vscode-generator-code#384]
Hello,

when I use the process that is wirtten on this [page](https://code.visualstudio.com/api/get-started/your-first-extension).

I press F5, it opens the Extension Development Host and when I write hello in the Command Palette (Ctrl+Shift+P) I get that: 
![image](https://user-images.githubusercontent.com/46788089/199271033-c3d8759c-c4ca-48d8-a73a-9a4bee9e6881.png)

Am I doing something wrong?

Thank you for your help
Best Regards

**Comment by aeschli** [comment]
That should work. Can you check the Logs if your extension could not be loaded (e.g. a syntax error in the package.json)

**Comment by luca1226** [comment]
I do find the issue:
When creating all the files. In the package.json, it has this line:
`"engines": {
    "vscode": "^1.72.0"
  }`

My vscode is at version 1.70.
It would be great maybe to check the vscode version and add the current version on the computer instead of automatically add the last version of vscode.
Something maybe to think about.
Thank you for your help Martin

**Comment by aeschli** [comment]
You can change that number backwards, but we recommend always to use the latest version of VS Code.
