### ISSUE TITLE
vscode.d.ts doesn't work with new Salsa-based language service

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode-generator-code#39]
* generate an extension that uses JavaScript
* use the typescript compiler to downlevel compile ES6 to ES5
* > you get many errors in vscode.raw.d.ts

**Comment by bpasero** [comment]
I am seeing compile errors already in vscode.d.ts without changing anything in the hello world JS extension. My jsconfig.json is configured to "target": "ES5"

> use the typescript compiler to downlevel compile ES6 to ES5

How do you set this up, what are the steps?

Anyhow, thankful for any hints how to resolve this (also @dbaeumer).

**Comment by jrieken** [comment]
I created a jsconfig.json files with compiler settings, like so:

```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "ES5",
        "noLib": true,
        "outDir": "out",
        "sourceMap": true
    },
    "exclude": [
        "out",
        "node_modules"
    ]
}
```

and then I run `tsc -p jsconfig.json -w` on the console. The issue is that there are conflicting declaration of Thenable and promise. I believe the custom works we do for either JS or TS isn't needed anymore

**Comment by bpasero** [comment]
Ok indeed we do no longer need the workarounds for JS vs TS extension.
