### ISSUE TITLE
Generator gives a Syntax error

### ISSUE THREAD

**Issue by macutko** [microsoft/vscode-generator-code#393]
Hi,

I followed the tutorial on https://code.visualstudio.com/api/get-started/your-first-extension and created a new web extension. When I hit `F5` I get a `SyntaxError: Unexpected token  in JSON at position 0` in my debug console. Obviously this means I have no Hello World command. Any ideas on how to fix this? 

I am running VS Code on linux - ubuntu 22.04 if that helps. 

Any help much appreciated!

**Comment by aeschli** [comment]
I'm not able to reproduce. Can you still see this?
