### ISSUE TITLE
Create extensions directly in .vscode\extensions\<extensionname> folder

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode-generator-code#4]
I don't think there is any reason we can't have the yo code generator create the extensions directly under the user's .vscode\extensions folder.  Right now they have to manually copy the generator output to be picked up by VS Code.

**Comment by peterblazejewicz** [comment]
> but we could offer to copy to the extensions folder at the end of the generator.

I think [`vsce`](https://github.com/Microsoft/vscode-vsce) CLI tool would be better option to this feature. It could have `link` method, just like NPM or Atom APM, which has `link` and `unlink` for development:
https://github.com/atom/apm/blob/master/src/link.coffee
https://github.com/atom/apm/blob/master/src/unlink.coffee.
This will expose similar pattern to developer known from other tools.

**Comment by wholroyd** [comment]
+1 on @peterblazejewicz's suggestion.

**Comment by bpasero** [comment]
+1 for doing this from vsce.
