### ISSUE TITLE
New extension has warning because it includes onCommand activation

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode-generator-code#401]
<img width="1420" alt="image" src="https://user-images.githubusercontent.com/2644648/215966183-f302bf90-781d-4c38-94ec-ba618957dc04.png">

We shouldn't have this activation event anymore

cc @joyceerhl

**Comment by joyceerhl** [comment]
@aeschli fixed this with https://github.com/microsoft/vscode-generator-code/commit/366fa08fdaab957e3f1d2e63287899d76eaf6e5d--thank you both!
