### ISSUE TITLE
The generator shouldn't add the activation event

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode-generator-code#422]
<img width="382" alt="image" src="https://github.com/microsoft/vscode-generator-code/assets/2644648/7a895c5b-fc77-41b9-8758-666b07873579">

In newer extensions we have implicit activation. That makes this line not needed anymore so we shouldn't include it in the generator.

**Comment by joyceerhl** [comment]
The generator doesn't generate this anymore https://github.com/microsoft/vscode-generator-code/blob/4eb254a03759ce2c4c5d9e6b670ce39a5524a3f3/generators/app/templates/ext-command-ts/package.json#L12-L13

**Comment by ViktorMachine** [comment]
So how do you use it

**Comment by TylerLeonhardt** [comment]
I had an old version 👍
