### ISSUE TITLE
Notebook extension broken

### ISSUE THREAD

**Issue by ChuckJonas** [microsoft/vscode-generator-code#446]
Running the `yo code` for the notebook template results in a project that doesn't build or run.

**Comment by aeschli** [comment]
The error is

`Cannot find module 'vscode-notebook-error-overlay'. Did you mean to set the 'moduleResolution' option to 'nodenext', or to add aliases to the 'paths' option?`

**Comment by aeschli** [comment]
@connor4312 I don't know how up-to date the note generator is. Feel free to remove it if it is outdated.

Note that for other generators we have integration tests that generate the extension, build it, and run the tests in to make sure all still works.

**Comment by aeschli** [comment]
@connor4312 Can you have a look?

**Comment by mootari** [comment]
Related: https://github.com/microsoft/vscode-notebook-error-overlay/issues/8
