### ISSUE TITLE
No matching version found for @types/vscode@^1.89.0 (New Extension template, TypeScript)

### ISSUE THREAD

**Issue by peteraritchie** [microsoft/vscode-generator-code#463]
Following https://code.visualstudio.com/api/get-started/your-first-extension at the time of writing this ends up with `No matching version found for @types/vscode@^1.89.0`. Going to npmjs.com (https://www.npmjs.com/package/@types/vscode) shows that the latest version is 1.88.0.

**Comment by aeschli** [comment]
This should work now, 1.89 is published.
