### ISSUE TITLE
Configured debug type 'extensionHost' is not supported.

### ISSUE THREAD

**Issue by thealjey** [microsoft/vscode-generator-code#465]
I'm trying to follow the [Your First Extension](https://code.visualstudio.com/api/get-started/your-first-extension) guide for the first time.
And the very first thing they tell you to do (`Inside the editor, open src/extension.ts and press F5`) results in the following:
![image](https://github.com/microsoft/vscode-generator-code/assets/2216553/aa69ae95-b831-4f8d-ab1b-ffd2e67923a8)
Obviously, the `Install extensionHost Extension` button doesn't help at all, because there's no such extension in the Marketplace.
...
Why does nothing ever work on the first try? 😭

**Comment by aeschli** [comment]
I tested that with a fresh install (using a new profile) all works.

Did you maybe disable the built-in extension `JavaScript Debugger`?
- open the extensions view
- type `@builtin JavaScript Debugger` in the search field
- make sure the extension is enabled

**Comment by aeschli** [comment]
Marking as closed
