### ISSUE TITLE
Error in PostInstall

### ISSUE THREAD

**Issue by derchirurg** [Microsoft/vscode-generator-code#60]
Hi,

I get the following error in PostInstall.

> 35522 verbose lifecycle myext@0.0.1~postinstall: CWD: C:\_temp\myext\myext
> 35523 silly lifecycle myext@0.0.1~postinstall: Args: [ '/d /s /c', 'node ./node_modules/vscode/bin/install' ]
> 35524 silly lifecycle myext@0.0.1~postinstall: Returned: code: 1  signal: null
> 35525 info lifecycle myext@0.0.1~postinstall: Failed to exec postinstall script
> 35526 warn myext@0.0.1 No repository field.
> 35527 verbose If you need help, you may report this error at:
> 35527 verbose     <https://github.com/npm/npm/issues>
> 35528 warn myext@0.0.1 No license field.
> 35529 verbose If you need help, you may report this error at:
> 35529 verbose     <https://github.com/npm/npm/issues>
> 35530 verbose stack Error: myext@0.0.1 postinstall: `node ./node_modules/vscode/bin/install`
> 35530 verbose stack Exit status 1
> 35530 verbose stack     at EventEmitter.<anonymous> (C:\Users\x\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:255:16)
> 35530 verbose stack     at emitTwo (events.js:106:13)
> 35530 verbose stack     at EventEmitter.emit (events.js:191:7)
> 35530 verbose stack     at ChildProcess.<anonymous> (C:\Users\x\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
> 35530 verbose stack     at emitTwo (events.js:106:13)
> 35530 verbose stack     at ChildProcess.emit (events.js:191:7)
> 35530 verbose stack     at maybeClose (internal/child_process.js:877:16)
> 35530 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
> 35531 verbose pkgid myext@0.0.1
> 35532 verbose cwd C:\_temp\myext\myext
> 35533 error Windows_NT 6.1.7601
> 35534 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\x\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
> 35535 error node v6.7.0
> 35536 error npm  v3.10.9
> 35537 error code ELIFECYCLE
> 35538 error myext@0.0.1 postinstall: `node ./node_modules/vscode/bin/install`
> 35538 error Exit status 1
> 35539 error Failed at the myext@0.0.1 postinstall script 'node ./node_modules/vscode/bin/install'.
> 35539 error Make sure you have the latest version of node.js and npm installed.
> 35539 error If you do, this is most likely a problem with the myext package,
> 35539 error not with npm itself.
> 35539 error Tell the author that this fails on your system:
> 35539 error     node ./node_modules/vscode/bin/install
> 35539 error You can get information on how to open an issue for this project with:
> 35539 error     npm bugs myext
> 35539 error Or if that isn't available, you can get their info via:
> 35539 error     npm owner ls myext
> 35539 error There is likely additional logging output above.
> 35540 verbose exit [ 1, true ]

What am I doing wrong?

**Comment by aeschli** [comment]
Sorry, no idea. Do you still see this?

**Comment by aeschli** [comment]
Closing for now. Please reopen if you still see this.
