### ISSUE TITLE
vscode extensions

### ISSUE THREAD

**Issue by fuciktomas** [Microsoft/vscode-generator-code#64]
Hi,
I'm install: "npm install -g yo generator-code" and run: "yo code", but i can't select template "New Extension Pack". This template is not in menu.

Thanks for help.

Tomas

**Comment by jdforsythe** [comment]
It looks like this was addressed:

https://github.com/Microsoft/vscode-generator-code/issues/63

and the relevant code:

https://github.com/Microsoft/vscode-generator-code/blob/master/generators/app/index.js#L81-L84

but it just hasn't been released. VS Code 1.9.0 release notes seems to say this is already released into the generator but it has not been updated to npm.

**Comment by aeschli** [comment]
1.10 got released in the meantime
