### ISSUE TITLE
Possible to keep this gen in sync with VScode releases?

### ISSUE THREAD

**Issue by metaleap** [Microsoft/vscode-generator-code#71]
VScode 1.11 introduces 3 new `enum` members to `vscodeCompletionItemKind`. But these won't be readily usable from inside a `yo code`-generated extension as of today with completely fresh installs of VScode, nodejs/npm, yo and generator-code (as it happens I'm setting up a new machine today ;)  --- when one creates a new ext within this "everything is latest version" setup, among all the screen outputs of `yo code` will be:

    Detected VS Code engine version: ^1.10.0
    Found minimal version that qualifies engine range: 1.10.0
    Fetching vscode.d.ts from: https://raw.githubusercontent.com/Microsoft/vscode/1.10.0/src/vs/vscode.d.ts
    vscode.d.ts successfully installed!

As far as I can tell from my end, manually fixing up the new extension's `package.json` to use:

    "engines": {
        "vscode": "^1.11.1"
    },
    "devDependencies": {
        "typescript": "^2.2.2",
        "vscode": "^1.1.0",
        "@types/node": "^7.0.12"
    }

and running `npm update` also regrettably does *nothing* to actually make such new API additions *actually available* (to IntelliSense *and* the TypeScript compiler) in an existing extension project..  :/

**Comment by aeschli** [comment]
The generator now queries the latest vscode version and uses it
