### ISSUE TITLE
I can't create a "New Code Snippets"

### ISSUE THREAD

**Issue by JonathanBergson** [Microsoft/vscode-generator-code#75]
![captura de tela 2017-05-23 as 13 10 18](https://cloud.githubusercontent.com/assets/6494405/26364699/884711ae-3fbb-11e7-929a-201963b20f3c.png)

**Comment by Kelvne** [comment]
I just re-created your steps and I was successful. Maybe you have an old version of the generator?

**Comment by third774** [comment]
I'm running into this exact same error. I have `generator-code@1.1.15` installed globally, and using `yo@2.0.0`. I'm running this on a Mac and have updated my global npm path to be `~/.npm-global`.

![screen shot 2017-07-26 at 1 56 49 pm](https://user-images.githubusercontent.com/8732191/28638398-5dd12dac-720a-11e7-9bd0-36b17e88ee97.png)

**Comment by JonathanBergson** [comment]
The first question `Folder name for import or none for new:` should not be filled.
