### ISSUE TITLE
Can't import a .tmTheme file if it has a space in its name

### ISSUE THREAD

**Issue by nathan-munchery** [Microsoft/vscode-generator-code#76]
Doesn't matter how I try to escape it, it bombs out with

```
Error: Uncaught, unspecified "error" event. (Problems loading theme: ENOENT: no such file or directory, open 'Some\ Theme.tmTheme')
    at constructor.emit (events.js:163:17)
    at Immediate.<anonymous> (/usr/local/lib/node_modules/generator-code/node_modules/yeoman-generator/lib/base.js:446:16)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
``` 

every single time.

And as a completely separate issue not really worthy of a bug report, why do I need to spend hours of my life creating a "publisher" just to import a color theme for my own personal usage?

**Comment by aeschli** [comment]
You can also install an extension locally:
Copy your extension to (or create a symbolic link to):
- Windows %USERPROFILE%\.vscode\extensions
- Mac ~/.vscode/extensions
- Linux ~/.vscode/extensions

Alternatively, we let you define workspace colors in the settings: 'workbench.colorCustomizations`.
This isn't available for token colors yet. The request is #27894.

**Comment by aeschli** [comment]
I'm not able to reproduce. Spaces in the name don't seem to matter, I can load these files. No escapes needed.
e.g. /home/aeschli/tmp/new file
I also added a test for it.
