### ISSUE TITLE
Can not enter name in my win10.

### ISSUE THREAD

**Issue by MyHerux** [Microsoft/vscode-generator-code#80]
I can't type any words when I go step 2 "what's your name of your extension?".
Type "enter key" is also nothing happened.
Thanks for help.

![](http://of0qa2hzs.bkt.clouddn.com/1497595330%281%29.jpg)

**Comment by aeschli** [comment]
I'm not able to reproduce. We use the standard yeoman input mechanisms here, so if you still see this file this against yeoman: http://yeoman.io/contributing/

**Comment by MyHerux** [comment]
I find this bug just because of the version for nodejs rather than windows.update the nodejs version can fix this problem.
