### ISSUE TITLE
Yeoman "generator-code" generates old-style tasks.json with warning

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-generator-code#81]
testing #29466:

![2017-06-27_17-42-39](https://user-images.githubusercontent.com/1898161/27596523-0d584e02-5b60-11e7-889d-66c539f18e25.png)

**Comment by dbaeumer** [comment]
@bpasero I noticed that as well this week and the only thing we should address is turing isWatching into isBackground. We shouldn't migrate to task 2.0.0 since it will force devs to use 1.14. We should wait one month at least.

**Comment by KamasamaK** [comment]
It has been almost 2 months. Any update on using 2.0.0?

**Comment by aeschli** [comment]
Fixed by https://github.com/Microsoft/vscode-generator-code/commit/62adbfa2f7fde828ad4554f87d381ed2bb3d57a7
