### ISSUE TITLE
EH debugging: use a better name for the launch config's preLaunchTask

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-generator-code#83]
(from a gitter question)

Currently the generated launch.json for the "hello world" extension uses a "preLaunchTask" named "npm" which confuses users, because they think that this is the raw "npm" command.

But this "npm" refers to the "npm" task configured in the task.json.
Only after understanding this connection it becomes clear what this "npm" really means:

```json
    // we run the custom script "compile" as defined in package.json
    "args": ["run", "compile", "--loglevel", "silent"],
```

I suggest that we rename the "npm" task to something more expressive like "compileAndWatch".

/cc @weinand

**Comment by dbaeumer** [comment]
We should wait a little with this and then convert the generator to tasks 2.0.0 with npm auto detection. I haven't done this since it would require extension writers to use 1.14. I thought we wait one release with this.

**Comment by aeschli** [comment]
The prelaunch tasks is now `"preLaunchTask": "npm: watch"`
