### ISSUE TITLE
Cannot Launch brand new extension

### ISSUE THREAD

**Issue by lashchev** [Microsoft/vscode-generator-code#88]
Generated "Hello, World!" TypeScript extension by following https://code.visualstudio.com/docs/extensions/example-hello-world instructions with VSC 1.16.1 x64 and on F5 - new instance of VSC starts with error:
`[${workspaceFolder}]: Error: ENOENT: no such file or directory, scandir 'C:\Program Files\Microsoft VS Code\${workspaceFolder}'
`
Also, debug console of the VSC with extension code has a lot of errors like this:
```
C:\Program Files\Microsoft VS Code\Code.exe --debugBrkPluginHost=39673 --debugId=ffa3cd2d-d039-4d95-8b06-8faf6f686681 --extensionDevelopmentPath=${workspaceFolder} 
SourceMaps.loadSourceMapContents: Could not download sourcemap from https://ticino.blob.core.windows.net/sourcemaps/27492b6bf3acb0775d82d2f87b25a93490673c6d/core/bootstrap.js.map
...
SourceMaps.loadSourceMapContents: Could not download sourcemap from https://ticino.blob.core.windows.net/sourcemaps/27492b6bf3acb0775d82d2f87b25a93490673c6d/extensions\merge-conflict\out/contentProvider.js.map
SourceMaps.loadSourceMapContents: Could not download sourcemap from https://ticino.blob.core.windows.net/sourcemaps/27492b6bf3acb0775d82d2f87b25a93490673c6d/extensions\merge-conflict\out/mergeDecorator.js.map

```
URLs are accessible fine in the browser.

**Comment by honzo0481** [comment]
I had the same issue. Replacing `workspaceFolder` with `workspaceRoot` in  launch.json worked for me.

**Comment by jonbesga** [comment]
`workspaceFolder` replaced `workspaceRoot` some commits ago: https://github.com/Microsoft/vscode/commit/efdc3280582369bb1dca98065d95c7ce994d6a47

Looks like we don't have the update yet.

**Comment by aeschli** [comment]
Fixed by https://github.com/Microsoft/vscode-generator-code/commit/5005543359db80f2db3c7485c36fe039021a157b

**Comment by mudlabs** [comment]
@aeschli, Not fixed. I'm getting the same error.

**Comment by mudlabs** [comment]
@aeschli, _belay_ that. Just had to update to ___1.38.1___
