### ISSUE TITLE
default enable javascript type checking to Yes?

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-generator-code#96]
testing https://github.com/Microsoft/vscode/issues/39257

When creating a JavaScript extension, I'm asked if I want to enable JS type checking in `jsconfig.json` but it defaults to No.  Is this deliberate? Is there a reason we wouldn't turn it on?

`Enable JavaScript type checking in 'jsconfig.json'? (y/N)`

**Comment by egamma** [comment]
@chrisdias unfortunately it is intentional. Having checking enabled gets frustrating when you use node modules for which there is no .d.ts files. There are still many of them. In this case the only way out is to pollute your code with @ts-ignore or to define a .d.ts file.
