### ISSUE TITLE
Yeoman generator failed to create all required scripts (I think)

### ISSUE THREAD

**Issue by jrwrigh** [microsoft/vscode-generator-code#99]
I was trying to make a Language Support extension for VS Code and ran into some issues with trying to use the `activationEvents`. VS Code demanded that I have a `main` specified, but the Yo Code generator didn't put anything there. I asked through [StackExchange](https://stackoverflow.com/q/48038136/7564988) and was told that the lack of an `extension.ts` maybe a bug or something. 

## Version Info:
Yo Code Generator: 1.1.22
OS: Windows 10
NPM: 5.5.1
VS Code: 1.19.1

## Steps to Recreate:

1. Install npm
2. Install Yo Code generator
3. Launch Yo Code generator and select new Language Support
4. Go through the generator without specifying a language to copy from

A zip file of the exported files can be seen below:
[ccl2.zip](https://github.com/Microsoft/vscode-generator-code/files/1595435/ccl2.zip)

Let me know if you have any questions.

**Comment by aeschli** [comment]
A language extension doesn't need a main. It's just adding sections to `package.json`.

Try the `TypeScript sample`
